root_path: /fs-computility/llm/shared/wangyikun/datasets/AD_Preference_0522
internembedder_datasets:
  - name: 0524_raw
    data_type: s2s
    task_type: Preference
    prompts: [""]
    sampling_ratio: 1.0